name: IBKRWatchApp
options:
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  IBKRWatchApp:
    type: application
    platform: iOS
    bundleId: com.example.IBKRWatchApp
    info:
      path: Info.plist
    sources:
      - IBKRWatchApp
    frameworks:
      - WatchConnectivity.framework
  IBKRWatchAppWatchApp:
    type: watch2App
    platform: watchOS
    bundleId: com.example.IBKRWatchApp.watchkitapp
    info:
      path: WatchApp/Info.plist
    dependencies:
      - target: IBKRWatchAppWatchExtension
    sources:
      - WatchApp
  IBKRWatchAppWatchExtension:
    type: watch2Extension
    platform: watchOS
    bundleId: com.example.IBKRWatchApp.watchkitapp.extension
    info:
      path: WatchExtension/Info.plist
    sources:
      - WatchExtension
    dependencies:
      - target: IBKRWatchApp
    frameworks:
      - WatchConnectivity.framework
