name: IBKRWatchApp
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  IBKRWatchApp:
    type: application
    platform: iOS
    bundleId: com.example.IBKRWatchApp
    info:
      path: Info.plist
    sources:
      - IBKRWatchApp
