name: IBKRWatchApp
options:
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
targets:
  IBKRWatchApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    bundleId: com.example.IBKRWatchApp
    info:
      path: Info.plist
    sources:
      - IBKRWatchApp
    frameworks:
      - WatchConnectivity.framework
    dependencies:
      - target: IBKRWatchAppWatchApp
        embed: true
  IBKRWatchAppWatchApp:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "10.0"
    bundleId: com.example.IBKRWatchApp.watchkitapp
    info:
      path: WatchApp/Info.plist
    dependencies:
      - target: IBKRWatchAppWatchExtension
    sources:
      - WatchApp
  IBKRWatchAppWatchExtension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "10.0"
    bundleId: com.example.IBKRWatchApp.watchkitapp.extension
    info:
      path: WatchExtension/Info.plist
    sources:
      - WatchExtension
    frameworks:
      - WatchConnectivity.framework
